### ISSUE TITLE
It seems that gaussian radius function has problem.

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/CenterNet-Lite#12]
https://github.com/yjh0410/CenterNet-Lite/blob/97e233d6afe852b72d2ef40df486ccf5fa5dd729/tools.py#L55-L75

Where is box_w?

**Comment by yjh0410** [comment]
Oh, no ! So stupid bug~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yjh0410/CenterNet-Lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 晚上9:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yjh0410/CenterNet-Lite] It seems that gaussian radius function has problem. (#12)





 
https://github.com/yjh0410/CenterNet-Lite/blob/97e233d6afe852b72d2ef40df486ccf5fa5dd729/tools.py#L55-L75
 
Where is box_w?
