### ISSUE TITLE
SPP is important to reproduce the performance in README?

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/CenterNet-Lite#15]
SPP is important to reproduce the performance in README?

**Comment by developer0hye** [comment]
@yjh0410 
What command do we run to reproduce the performance in README?

**Comment by yjh0410** [comment]
This is a good question. I need to train again without SPP. I will update my README. The command to reproduce my result is “python train.py —cuda”.



发自我的iPhone


------------------ Original ------------------
From: Yonghye Kwon ***@***.***&gt;
Date: Tue,Mar 23,2021 7:52 AM
To: yjh0410/CenterNet-Lite ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [yjh0410/CenterNet-Lite] SPP is important to reproduce the performance in README? (#15)





 
SPP is important to reproduce the performance in README?

**Comment by developer0hye** [comment]
@yjh0410 
Thanks!
