### ISSUE TITLE
i found that you didn't maintain the aspect ratio of  the image during traning. This's different from the original code, it will cause the result?

### ISSUE THREAD

**Issue by hyaihjq** [yjh0410/CenterNet-Lite#2]

**Comment by yjh0410** [comment]
Very happy to receive your question！
It will cause the resule？I'm not sure.
But, when I reproduced YOLOv3, I didn't keep the aspect ratio during training，either.
Then, I got 37AP higher than official 33AP.
So, I think it doesn't matter.
On the other hand, My CenterNet-Lite isn't 100% same to official CenterNet such as the way to learn offset and size. Even so, my model gets 25 AP and 44.8 AP50 compared to (official) 28AP and 44.9AP.
