### ISSUE TITLE
cocodataset代码疑问

### ISSUE THREAD

**Issue by hukv1990** [yjh0410/CenterNet-Lite#9]
cocodataset.py 
     cls_id = self.class_ids.index(label_ind)

请问这句话的作用是什么？

**Comment by yjh0410** [comment]
您好。这个是因为COCO中的类别不止80个，但OD任务中，COCO只用80个类别，因此，这句话的作用就是确保所使用的类别是对应到80这个范围内。最终获得的cls_id才是在1-80范围。

**Comment by hukv1990** [comment]
好的，谢谢。我把voc的数据转成了coco格式进行训练，mAP只能到0.70左右，输出的模型用您这边的voc那套代码测出来mAP是0.75。
